name: Maven Tests
on: [push]
jobs:
  maven-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v4
      - name: Cucumber
        uses: cucumber-expressions@v17.1.0
        with:
          start: mvn test
